server:
  port: 8083

spring:
  application:
    name: order

  datasource:
    url: jdbc:mysql://localhost:3306/microservices_Orders?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  boot:
    admin:
      client:
        url: http://localhost:8088

  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.microservices: DEBUG
    feign: DEBUG
